version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfilebackend
    # container_name: fastapi_app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn chatbot:app --host 0.0.0.0 --port 8000
    env_file:
      - .env

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfilefrontend
    # container_name: streamlit_app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py
    env_file:
      - .env
